name = input("Who the hell are you ? ")
city = input("Where do you live ? ")
age = input("What is your age ? ")
hobby = input("What is your Hobby ? ")
movie = input("What is your favrouit movie ? ")
food = input("What is your favrouit food ? ")

print("\n")
print("----YOUR DETAILS----")
print("NAME : ",name)
print("CITY : ",city)
print("AGE : ",age)
print("HOBBY : ",hobby)
print("MOVIE : ",movie)
print("FOOD : ",food)
print("----THE END----")
print("\n")